defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  host: localhost
  encoding: utf8

development:
  <<: *defaults
  database: bali_hotels_development

test: &test
  <<: *defaults
  database: bali_hotels_test

cucumber:
  <<: *test